import tensorflow as tf
from tensorflow import nn
import numpy
test_data = numpy.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])
inputdata = tf.placeholder('float',[None, 2,3])
x1 = tf.transpose(inputdata,[1,0,2])
x2 = tf.reshape(x1,[-1,3])
x3 = tf.split(0,2,x2)
x4 = tf.reduce_mean(x2)
pred_1 = tf.argmax(x2, 1)
pred_0 = tf.argmax(x2, 0)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    test_data = test_data.reshape((2,2,3))
    out_1 = sess.run(inputdata,feed_dict={inputdata:test_data})
    print(out_1)
    out_2 = sess.run(x1,feed_dict={inputdata:test_data})
    print(out_2)
    out_3 = sess.run(x2,feed_dict={x1:out_2})
    print(out_3)
    out_4 = sess.run(x3,feed_dict={x2:out_3})
    print(out_4)
    out_4_2 = sess.run(x4, feed_dict = {x2:out_3})
    print(out_4_2)
    out_4_3 = sess.run(pred_0, feed_dict = {x2:out_3})
    print(out_4_3)
lstm_cell = nn.rnn_cell.BasicLSTMCell(20)
print(lstm_cell)
